Issue serve static java script bundle instead of yarn dev server in dockerfile
eclipse-tractusx/demand-capacity-mgmt pull request #51
Opened 2024-02-01 15:52 UTC by Bailonis

This PR serves to help keep our project aligned with the TRGs and other open-source policies.

In this case, we have build the app into static JavaScript bundles and place them in a nginx-unprivileged container

fix #12

2024-02-02 08:19 UTC, SebastianBezold requested changes

2024-02-02 08:19 UTC, SebastianBezold commented on build/frontend/Dockerfile
> +RUN apk update && apk add --no-cache bash
As stated in our release guidelines, We must not alter the base images of our published images.

2024-02-02 08:19 UTC, SebastianBezold commented on build/frontend/NOTICE.md
> +- GitHub: [https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend](https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend)
Wrong link

2024-02-02 08:19 UTC, SebastianBezold commented on build/frontend/NOTICE.md
> +- Dockerfile: [https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend/blob/main/Dockerfile](https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend/blob/main/Dockerfile)
Wrong link -> repo name does not match

2024-02-06 10:11 UTC, Bailonis commented on build/frontend/NOTICE.md
> +- GitHub: [https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend](https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend)
remove file

2024-02-06 10:11 UTC, Bailonis commented on build/frontend/NOTICE.md
> +- Dockerfile: [https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend/blob/main/Dockerfile](https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend/blob/main/Dockerfile)
file removed

2024-02-07 08:35 UTC, SebastianBezold commented
Hi @Bailonis, as with your other PRs, this one also contains changes, that are not related to the issue that should be fixed.
Please isolate the changes

2024-02-07 09:26 UTC, closed without merging