2nd Eclipse Tractus-X Community Days Contribution
eclipse-tractusx/demand-capacity-mgmt pull request #79
Opened 2024-05-22 09:01 UTC by ClosedSourcerer

## Description
- Increased Deployability
- Fixed minor Issues
- TRG 8 will be taken care off with a seperate PR into the Upstream Repository.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-05-22 09:08 UTC, carslen commented
> The build is failing due to prettier. Need to rebase once #72 merged in the main branch again

Please do a new PR with these changes as this PR has been reverted after it has been merged accidentaly.

2024-05-22 09:16 UTC, carslen requested changes
Please fix [failing ECA check](https://api.eclipse.org/git/eca/status/gh/eclipse-tractusx/demand-capacity-mgmt/79).

Also update `DEPENDENCIES_BACKEND` file as it seems that new deps has been added.

2024-05-22 13:21 UTC, nitin-vavdiya commented
> > The build is failing due to prettier. Need to rebase once #72 merged in the main branch again
> 
> Please do a new PR with these changes as this PR has been reverted after it has been merged accidentaly.

New PR: https://github.com/eclipse-tractusx/demand-capacity-mgmt/pull/80

2024-05-23 09:56 UTC, evegufy requested changes
Hi @ClosedSourcerer @nitin-vavdiya nice contribution in general!
Agree with all comments from @carslen and one small comment from my side

2024-05-23 09:56 UTC, evegufy commented on demand-capacity-mgmt-backend/src/main/resources/db/migration/V16__initial_data.sql
> +
Please add file header

2024-05-23 12:22 UTC, nitin-vavdiya commented on demand-capacity-mgmt-backend/src/main/resources/db/migration/V16__initial_data.sql
> +
Fixed with: https://github.com/eclipse-tractusx/demand-capacity-mgmt/pull/79/commits/889cbaa5306f96acf87b9fde5e6c81e131dd8415

2024-05-24 05:41 UTC, nitin-vavdiya commented
> Please fix [failing ECA check](https://api.eclipse.org/git/eca/status/gh/eclipse-tractusx/demand-capacity-mgmt/79).
> 
> Also update `DEPENDENCIES_BACKEND` file as it seems that new deps has been added.

Thanks for reviewing this PR.
Regarding `DEPENDENCIES_BACKEND`, it will be added with [this PR](https://github.com/eclipse-tractusx/demand-capacity-mgmt/pull/80/files#diff-f3185f05c8d717818f75bbdd6a0db01f563bd1910d338bad684421fd1d0ee36c)

2024-05-24 14:27 UTC, carslen commented
> > Please fix [failing ECA check](https://api.eclipse.org/git/eca/status/gh/eclipse-tractusx/demand-capacity-mgmt/79).
> > Also update `DEPENDENCIES_BACKEND` file as it seems that new deps has been added.
> 
> Thanks for reviewing this PR. Regarding `DEPENDENCIES_BACKEND`, it will be added with [this PR](https://github.com/eclipse-tractusx/demand-capacity-mgmt/pull/80/files#diff-f3185f05c8d717818f75bbdd6a0db01f563bd1910d338bad684421fd1d0ee36c)

Sorry to disagree, but if you introduce a new dependency with a PR, you need to update the DEPENCENCIES file accordingly. A reference to another PR is not valid.

2024-06-21 10:42 UTC, evegufy requested changes
There are suddenly 888 commits showing, could you please clean this up?
That's probably also the reason why GitGuardian comes up with those findings and once that's clean up, I assume the finding will be gone.
But in general, if GitGuardian reveals findings they need to documented as what they are in the incident management section (either real - and in that case they need to revoked immediately  - or false positive/test) of GitGuardian.

Also, please re-request the review once there should be reviewed again, otherwise reviewers can't be aware that the pull request should be reviewed again.

2024-06-21 11:11 UTC, nitin-vavdiya commented
> There are suddenly 888 commits showing, could you please clean this up? That's probably also the reason why GitGuardian comes up with those findings and once that's clean up, I assume the finding will be gone. But in general, if GitGuardian reveals findings they need to documented as what they are in the incident management section (either real - and in that case they need to revoked immediately - or false positive/test) of GitGuardian.
> 
> Also, please re-request the review once there should be reviewed again, otherwise reviewers can't be aware that the pull request should be reviewed again.

I think I mashed up with the PR  and sorry for that
"There are suddenly 888 commits showing"  > I rebased this PR that's why I think 
Does closing this PR and creating fresh PR from my owned form repo make sense?

2024-07-02 11:48 UTC, evegufy commented
> > There are suddenly 888 commits showing, could you please clean this up? That's probably also the reason why GitGuardian comes up with those findings and once that's clean up, I assume the finding will be gone. But in general, if GitGuardian reveals findings they need to documented as what they are in the incident management section (either real - and in that case they need to revoked immediately - or false positive/test) of GitGuardian.
> > Also, please re-request the review once there should be reviewed again, otherwise reviewers can't be aware that the pull request should be reviewed again.
> 
> I think I mashed up with the PR and sorry for that "There are suddenly 888 commits showing" > I rebased this PR that's why I think Does closing this PR and creating fresh PR from my owned form repo make sense?

Hi @nitin-vavdiya rebasing with 800 + commits to drop can be tedious, opening a new pull request is fine (please reference to this one in the description so that we don't loose the discussions).

2024-07-03 04:52 UTC, nitin-vavdiya commented
> > > There are suddenly 888 commits showing, could you please clean this up? That's probably also the reason why GitGuardian comes up with those findings and once that's clean up, I assume the finding will be gone. But in general, if GitGuardian reveals findings they need to documented as what they are in the incident management section (either real - and in that case they need to revoked immediately - or false positive/test) of GitGuardian.
> > > Also, please re-request the review once there should be reviewed again, otherwise reviewers can't be aware that the pull request should be reviewed again.
> > 
> > 
> > I think I mashed up with the PR and sorry for that "There are suddenly 888 commits showing" > I rebased this PR that's why I think Does closing this PR and creating fresh PR from my owned form repo make sense?
> 
> Hi @nitin-vavdiya rebasing with 800 + commits to drop can be tedious, opening a new pull request is fine (please reference to this one in the description so that we don't loose the discussions).

New PR : https://github.com/eclipse-tractusx/demand-capacity-mgmt/pull/102
@Phil91 We can close this PR

2024-07-03 08:05 UTC, closed without merging