Frontend fully conected to backend
eclipse-tractusx/demand-capacity-mgmt pull request #8
Opened 2023-08-22 16:03 UTC by Bailonis

In this pr we did all the connection from the backend to the frontend, so it may have some big changes, but from now one, the changes would be small

2023-08-23 07:02 UTC, SebastianBezold requested changes

2023-08-23 07:06 UTC, SebastianBezold commented
Hi @Bailonis , i have some comments about the changes, please have a look at them.
Also, it would be great if someone from your team could do a content review, since I cannot answer things like "are all wanted features included", "are all the unit-tests added"
See also: [Developer Hub: Code Reviews](https://eclipse-tractusx.github.io/docs/oss/code-reviews)

2023-08-23 07:13 UTC, SebastianBezold commented
I created a `vet-project` IP issue to check the PR, since is quite big: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10164.

2023-08-23 08:22 UTC, Bailonis commented on .github/workflows/veracode-pipeline.yml
> -    branches: [ "main" ]
Done

2023-08-23 08:23 UTC, Bailonis commented on demand-capacity-mgmt-backend/src/main/java/org/eclipse/tractusx/demandcapacitymgmt/demandcapacitymgmtbackend/entities/enums/CapacityGroupStatus.java
Done

2023-08-23 08:26 UTC, Bailonis commented on demand-capacity-mgmt-backend/src/main/java/org/eclipse/tractusx/demandcapacitymgmt/demandcapacitymgmtbackend/entities/enums/MaterialDemandStatus.java
Done
![image](https://github.com/eclipse-tractusx/demand-capacity-mgmt/assets/72702458/ea5f85cd-a24f-476c-b7a4-472c6be79f8e)

2023-08-23 08:28 UTC, Bailonis commented on .github/workflows/veracode-pipeline.yml
> -    branches: [ "main" ]
![image](https://github.com/eclipse-tractusx/demand-capacity-mgmt/assets/72702458/488cf2fb-77dd-4810-903f-d2d9abf898bb)

2023-08-23 08:29 UTC, Bailonis commented on demand-capacity-mgmt-frontend/src/components/demands/DemandPage.tsx
done
![image](https://github.com/eclipse-tractusx/demand-capacity-mgmt/assets/72702458/f989da39-5c58-4aa5-a868-a49cc9219da1)

2023-08-24 08:19 UTC, Ruskyy commented
Nothing to point from my side.
Other than the nice finds from @SebastianBezold.
Unit Tests and Features were already pre discussed in code review, and are approved !

2023-08-25 12:59 UTC, SebastianBezold commented
IP issue resolved without findings! Will merge

2023-08-25 12:59 UTC, merged