fix: removed unused entitys
eclipse-tractusx/demand-capacity-mgmt pull request #9
Opened 2023-08-25 13:48 UTC by Bailonis

Unit Tests and Features were already pre discussed in code review, and are approved !

2023-08-25 18:00 UTC, SebastianBezold requested changes

2023-08-25 18:00 UTC, SebastianBezold commented on index.yaml
Again accidentally added?

2023-08-25 18:02 UTC, SebastianBezold commented
Hi @Bailonis, I added some review comments. Please have a look. Also, as with the other PR, please ask someone from your team for a review on the changes. I cannot tell, if the things you removed should be removed and if the DB scripts are correctly altered

2023-08-26 11:58 UTC, Bailonis commented on demand-capacity-mgmt-backend/src/main/java/org/eclipse/tractusx/demandcapacitymgmt/demandcapacitymgmtbackend/services/impl/WeekBasedMaterialServiceImpl.java
> +        //        Optional<SupplierEntity> supplierEntityOpt = supplierRepository.findById(1l);
Resolved

2023-08-26 11:58 UTC, Bailonis commented on demand-capacity-mgmt-backend/src/main/java/org/eclipse/tractusx/demandcapacitymgmt/demandcapacitymgmtbackend/services/impl/WeekBasedCapacityGroupServiceImpl.java
> +        //        Optional<CustomerEntity> supplierEntityOpt = customerRepository.findById(1l);
Resolved

2023-08-26 12:02 UTC, Bailonis commented on index.yaml
Resolved

2023-08-26 12:40 UTC, Bailonis commented on charts/charts/Chart.yaml
No, if we do not have that chart, the workflow for the backend builder will not work, because it says this folder does not have a Chart, but i can give it another name and description

2023-08-26 12:42 UTC, Bailonis commented on charts/charts/Chart.yaml
Resolved

2023-08-26 12:49 UTC, Bailonis commented on charts/charts/demand-capacity-management-backend/templates/pvc.yaml
resolved

2023-08-26 13:00 UTC, Bailonis commented on charts/charts/demand-capacity-management-backend/templates/deployment.yaml
> +
resolved

2023-08-26 18:13 UTC, SebastianBezold commented on charts/charts/Chart.yaml
This is not resolved :) If you're workflow complains about it, it clearly shows, that there is something wrong with your workflow. `/charts/charts` -> this means you have a Chart called `charts`. Is it possible, that a path declaration in your workflow is wrong? Keep in mind: Chart releaser is already looking at the `/charts` directory, so no need to specify `/charts`  in a path for chart-releaser action

2023-08-26 18:28 UTC, SebastianBezold commented on charts/charts/Chart.yaml
Ok i think I was a bit confused here, Your chart directory structure is a bit off i think.
In my opinion, you have two options to approach your Chart

1) Flat kubernetes manifests for frontend and backend in a single chart

```
<repo>
└───charts
    └───demand-capacity-management
        └───Chart.yaml
        └───templates
            └─── deployment-frontend.yaml
            └─── deployment-backend.yaml
            └─── service-frontend.yaml
            └─── service-backend.yaml
```

2) Build subcharts for frontend and backend and use them as dependencies of a product Chart

``` 
<repo>
└───charts
    └───demand-capacity-management
        └───Chart.yaml     <-- Does contain dcm-frontend and dcm-backend as dependency
        └───templates
            <empty>
        └───charts
            └─── dcm-frontend
                └─── Chart.yaml
                └───templates
                    └───deployment.yaml
                    ...
            └─── dcm-backend
                └─── Chart.yaml
                └───templates
                    └───deployment.yaml
                    ...
```

2023-08-28 07:58 UTC, Bailonis commented on charts/charts/Chart.yaml
Hi @SebastianBezold thanks for the input, I will follow your advice!

2023-09-06 06:46 UTC, SebastianBezold commented
Hi @Bailonis,

I could merge this PR, but the chart directory structure still seems to be odd.

`/charts/charts/` is wrong. It should be `/chart/demand-capacity-management` should be the goal

2023-09-06 06:46 UTC, merged